name: Deploy Supabase Ledger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4 # or your version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="supabase_access_token=${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
                             -var="org_id=${{ secrets.SUPABASE_ORG_ID }}" \
                             -var="db_password=${{ secrets.SUPABASE_DB_PASSWORD }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve \
                             -var="supabase_access_token=${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
                             -var="org_id=${{ secrets.SUPABASE_ORG_ID }}" \
                             -var="db_password=${{ secrets.SUPABASE_DB_PASSWORD }}"
