name: Release (Production)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      TF_VAR_linked_project: ${{ secrets.PRODUCTION_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}

    defaults:
      run:
        working-directory: supabase/remotes

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - run: terraform init -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" -backend-config='endpoints={s3="${{ secrets.TERRAFORM_BACKEND_ENDPOINT }}"}' -backend-config="access_key=${{ secrets.TERRAFORM_BACKEND_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.TERRAFORM_BACKEND_SECRET_KEY }}"
      - run: terraform apply -auto-approve -no-color -var="supabase_access_token=${{ secrets.SUPABASE_ACCESS_TOKEN }}" -var="org_id=${{ secrets.SUPABASE_ORG_ID }}" -var="db_password=${{ secrets.SUPABASE_DB_PASSWORD }}" -var="project_name=${{ secrets.SUPABASE_PROJECT_NAME }}"
      - name: Export Supabase Project ID
        id: export_project_id
        run: |
          echo "SUPABASE_PROJECT_ID=$(terraform output -raw supabase_project_id)" >> ${{ github.env }}

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref "$(terraform output -raw supabase_project_id)"
      - run: supabase db push
